[theme]
base = "light"
font = "sans-serif"
headingFont = "sans-serif"
primaryColor = "#38BDF8"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EFF8FE"
textColor = "#0F172A"
linkColor = "#0284C7"
codeBackgroundColor = "#EAF7FF"
borderColor = "#D7EAF6"
baseRadius = "large"
buttonRadius = "large"
showWidgetBorder = true
showSidebarBorder = true

[theme.light]
primaryColor = "#38BDF8"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EFF8FE"
textColor = "#0F172A"
linkColor = "#0284C7"
codeBackgroundColor = "#EAF7FF"
borderColor = "#D7EAF6"

[theme.light.sidebar]
backgroundColor = "#EFF8FE"
secondaryBackgroundColor = "#E4F4FE"
textColor = "#0F172A"
primaryColor = "#38BDF8"
borderColor = "#D7EAF6"

[theme.dark]
primaryColor = "#38BDF8"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#17243A"
textColor = "#E2E8F0"
linkColor = "#7DD3FC"
codeBackgroundColor = "#17243A"
borderColor = "#2A3B53"

[theme.dark.sidebar]
backgroundColor = "#101B30"
secondaryBackgroundColor = "#17243A"
textColor = "#E2E8F0"
primaryColor = "#38BDF8"
borderColor = "#2A3B53"
